export const FETCH_KUNA_REQUEST = 'FETCH_KUNA_REQUEST'
export const FETCH_KUNA_UPDATE = 'FETCH_KUNA_UPDATE'
export const FETCH_KUNA_FAILURE = 'FETCH_KUNA_FAILURE'

export const FETCH_MARKET_REQUEST = 'FETCH_MARKET_REQUEST'
export const FETCH_MARKET_UPDATE = 'FETCH_MARKET_UPDATE'
export const FETCH_MARKET_FAILURE = 'FETCH_MARKET_FAILURE'

export const CHANGE_UAH_VALUE = 'CHANGE_UAH_VALUE'